#!/usr/bin/ruby

class SubDlTrigger
  attr_accessor :id
  attr_accessor :name
  attr_accessor :saveFolder
  attr_accessor :fullName
  attr_accessor :files

	def initialize(arguments)
		@id = arguments[0]
		@name = arguments[1]
		@saveFolder = arguments[2]
    @fullName = File.expand_path("#{@saveFolder}/#{@name}")
    @extensions = ['.mkv','.mpeg','.mpg','.avi']
    @files = Array.new
  end

 def shellescape(str)
    return "''" if str.empty?
    str = str.dup
    str.gsub!(/([^A-Za-z0-9_\-.,:\/@\n])/n, "\\\\\\1")
    str.gsub!(/\n/, "'\n'")
    return str
  end

  def download
  end

  def isVideoFile(name)
    @extensions.include?(File.extname(name).downcase)
  end

  def run
    if File.directory?(@fullName) then
      Dir.glob("#{shellescape(@fullName)}/*",0).each { |entry|
        @files << entry if isVideoFile(entry)
      }
    else
      @files << shellescape(entry) if isVideoFile(entry)
    end

    @files.each{ |entry|
      cmd = "periscope -l en '#{entry}'"
      %x[#{cmd}>>/dev/null 2>&1]
    }
  end

end

if ARGV.length == 3 then
  dl = SubDlTrigger.new(ARGV)
  dl.run
else
  puts "meep!"
end

